exports.members = [
	{
            "id":"0",
            "title": "Governor",
            "name": "Gary R. Herbert",
            "city": "Salt Lake City",
            "state": "Utah",
            "address": "350 North State Street, Suite 200 P.O. Box 142220",
            "zip":"84114-2220",
            "phone": 8015381000,
            "tollFree": "8017052464",
            "officeHours": "Mon-Fri, 8am-5pm",
            "fax": "NA",
            "website": "https://www.utah.gov/governor/",
            "email": "",
            "image": "http://business.utah.gov/wp-content/uploads/198-Governor.jpg",
            "category":"UT"
        },
        {
            "id":"1",
            "title": "Lieutenant Governor",
            "name": "Spencer J. Cox",
            "city": "Salt Lake City",
            "state": "Utah",
            "address": "Utah State Capitol Complex, Suite 220 P.O. Box 142325",
            "zip":"84114-2325",
            "phone": 8015381040,
            "tollFree": "",
            "officeHours": "Mon-Fri, 7am-8pm Sat-Sun, 8am-6pm",
            "fax": "8015381133",
            "website": "https://www.utah.gov/ltgovernor/",
            "email": "",
            "image": "http://thinkutah.org/wp-content/uploads/2015/06/lt_gov_s_cox_o_14051.jpg",
            "category":"UT"
        },
        {
            "id":"2",
            "title": "Executive Director",
            "name": "Q. Val Hale",
            "city": "Salt Lake City",
            "state": "Utah",
            "address": "60 E. South Temple, 3rd Floor",
            "zip":"84114-2220",
            "phone": 8015388680,
            "tollFree": "8552049046",
            "officeHours": "Mon-Fri, 8am-5pm",
            "fax": "8015388888",
            "website": "http://business.utah.gov/",
            "email": "",
            "image": "http://business.utah.gov/wp-content/uploads/Val-300px.jpg",
            "category":"Utah Governor's Office of Economic Development"
        },
        {
            "id":"3",
            "title": "Senator",
            "name": "Mike Lee",
            "city": "Salt Lake City",
            "state": "Utah",
            "address": "125 State St # 4225",
            "zip":"84138",
            "phone": 8015245933,
            "tollFree": "",
            "officeHours": "",
            "fax": "",
            "website": "http://www.lee.senate.gov/public/",
            "email": "",
            "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Mike_Lee_official_portrait_112th_Congress.jpg/220px-Mike_Lee_official_portrait_112th_Congress.jpg",
            "category":"Utah Senator"
        },
        {
            "id":"4",
            "title": "Senator",
            "name": "Orrin Hatch",
            "city": "Salt Lake City",
            "state": "Utah",
            "address": "125 S State St # 8402",
            "zip":"84138",
            "phone": 8015244380,
            "tollFree": "",
            "officeHours": "",
            "fax": "",
            "website": "http://www.lee.senate.gov/public/",
            "email": "",
            "image": "https://upload.wikimedia.org/wikipedia/commons/d/df/Orrin_Hatch_official_photo.jpg",
            "category":"Utah Senator"
        }
];